[package]
name = "rist_core"
version = "0.1.0"
edition = "2021"

[dependencies]
rist_macros = { path = "../rist_macros"}
rvemu = "0.0.11"
itertools = "0.12.1"
phf = { version = "0.11.2", features = ["macros"] }
constcat = "0.4.1"
owo-colors = "4.0.0"