[package]
name = "rist_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.67"
syn = "2.0.48"
quote = "1.0.35"
serde = { version = "1.0.196", features = ["derive"] }
serde_yaml = "0.9.31"